INSERT INTO sys_continents (sys_continent_id, sys_continent_name) VALUES
('AF', 'Africa'),
('AS', 'Asia'),
('EU', 'Europe'),
('NA', 'North America'),
('SA', 'South America'),
('OC', 'Oceania'),
('AN', 'Antarctica');

INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name, sys_country_capital, sys_phone_code, sys_currency_name, sys_currency_cents, sys_currency_code) VALUES
('AF', 'AO', 'AGO', '024', 'Angola', 'Luanda', '+244', 'kwanza', 'lwei', 'AOA'),
('AF', 'BF', 'BFA', '854', 'Burkina Faso', 'Ouagadougou', '+226', 'CFA franc', 'centime', 'XOF'),
('AF', 'BI', 'BDI', '108', 'Burundi', 'Bujumbura', '+257', 'Burundi franc', 'centime', 'BIF'),
('AF', 'BJ', 'BEN', '204', 'Benin', 'Porto Novo13', '+229', 'CFA franc', 'centime', 'XOF'),
('AF', 'BW', 'BWA', '072', 'Botswana', 'Gaborone', '', 'pula', 'thebe', 'BWP'),
('AF', 'CD', 'COD', '180', 'Democratic Republic of Congo', 'Kinshasa', '+243', 'Congolese franc', 'centime', 'CDF'),
('AF', 'CF', 'CAF', '140', 'Central African Republic', 'Bangui', '+236', 'CFA franc', 'centime', 'XAF'),
('AF', 'CG', 'COG', '178', 'Republic of Congo', 'Brazzaville', '+242', 'CFA franc', 'centime', 'XAF'),
('AF', 'CI', 'CIV', '384', 'Cote d Ivoire', 'Yamoussoukro30', '+225', 'CFA franc', 'centime', 'XOF'),
('AF', 'CM', 'CMR', '120', 'Cameroon', 'Yaoundé', '+237', 'CFA franc', 'centime', 'XAF'),
('AF', 'CV', 'CPV', '132', 'Cape Verde', 'Praia', '+238', 'Cape Verde escudo', 'centavo', 'CVE'),
('AF', 'DJ', 'DJI', '262', 'Djibouti', 'Djibouti', '+253', 'Djibouti franc', 'centime', 'DJF'),
('AF', 'DZ', 'DZA', '012', 'Algeria', 'Algiers', '+213', 'Algerian dinar', 'centime', 'DZD'),
('AF', 'EG', 'EGY', '818', 'Egypt', 'Cairo', '+20', 'Egyptian pound', 'piastre', 'EGP'),
('AF', 'EH', 'ESH', '732', 'Western Sahara', 'Al aaiun', '', 'Moroccan dirham', 'centime', 'MAD'),
('AF', 'ER', 'ERI', '232', 'Eritrea', 'Asmara', '+291', 'nakfa', 'centime', 'ERN'),
('AF', 'ET', 'ETH', '231', 'Ethiopia', 'Addis Ababa', '+251', 'Ethiopian birr', 'cent', 'ETB'),
('AF', 'GA', 'GAB', '266', 'Gabon', 'Libreville', '+241', 'CFA franc39', 'centime', 'XAF'),
('AF', 'GH', 'GHA', '288', 'Ghana', 'Accra', '+233', 'cedi', 'pesewa', 'GHC'),
('AF', 'GM', 'GMB', '270', 'Gambia', 'Banjul', '+220', 'dalasi', 'butut', 'GMD'),
('AF', 'GN', 'GIN', '324', 'Guinea', 'Conakry', '+224', 'Guinean franc', '-', 'GNF'),
('AF', 'GQ', 'GNQ', '226', 'Equatorial Guinea', 'Malabo', '+240', 'CFA franc', 'centime', 'XAF'),
('AF', 'GW', 'GNB', '624', 'Guinea-Bissau', 'Bissau', '+245', 'CFA franc', 'centime', 'XOF'),
('AF', 'KE', 'KEN', '404', 'Kenya', 'Nairobi', '+254', 'Kenyan shilling', 'cent', 'KES'),
('AF', 'KM', 'COM', '174', 'Comoros', 'Moroni', '+269', 'Comorian franc', 'centime', 'KMF'),
('AF', 'LR', 'LBR', '430', 'Liberia', 'Monrovia', '+231', 'Liberian dollar', 'cent', 'LRD'),
('AF', 'LS', 'LSO', '426', 'Lesotho', 'Maseru', '+266', 'loti', 'sente', 'LSL'),
('AF', 'LY', 'LBY', '434', 'Libyan Arab Jamahiriya', 'Tripoli', '+218', 'Libyan dinar', 'dirham', 'LYD'),
('AF', 'MA', 'MAR', '504', 'Morocco', 'Rabat', '+212', 'Moroccan dirham', 'centime', 'MAD'),
('AF', 'MG', 'MDG', '450', 'Madagascar', 'Antananarivo', '+261', 'Malagasy franc', 'centime', 'MGF'),
('AF', 'ML', 'MLI', '466', 'Mali', 'Bamako', '+223', 'CFA franc47', 'centime', 'XOF'),
('AF', 'MR', 'MRT', '478', 'Mauritania', 'Nouakchott', '+222', 'Mauritanian ouguiya', 'khoum', 'MRO'),
('AF', 'MU', 'MUS', '480', 'Mauritius', 'Port Louis', '+230', 'Mauritian rupee', 'cent', 'MUR'),
('AF', 'MW', 'MWI', '454', 'Malawi', 'Lilongwe', '+265', 'Malawian kwacha', 'tambala', 'MWK'),
('AF', 'MZ', 'MOZ', '508', 'Mozambique', 'Maputo', '+258', 'metical', 'centavo', 'MZM'),
('AF', 'NA', 'NAM', '516', 'Namibia', 'Windhoek', '+264', 'Namibian dollar', 'cent', 'NAD'),
('AF', 'NE', 'NER', '562', 'Niger', 'Niamey', '+227', 'CFA franc', 'centime', 'XOF'),
('AF', 'NG', 'NGA', '566', 'Nigeria', 'Abuja58', '+234', 'naira', 'kobo', 'NGN'),
('AF', 'RE', 'REU', '638', 'Reunion', 'Saint-Denis', '+262', 'euro', 'cent', 'EUR'),
('AF', 'RW', 'RWA', '646', 'Rwanda', 'Kigali', '+250', 'Rwandese franc', 'centime', 'RWF'),
('AF', 'SC', 'SYC', '690', 'Seychelles', 'Victoria', '+248', 'Seychelles rupee', 'cent', 'SCR'),
('AF', 'SD', 'SDN', '736', 'Sudan', 'Khartoum', '+249', 'Sudanese dinar', 'piastre', 'SDD'),
('AF', 'SH', 'SHN', '654', 'Saint Helena', 'Jamestown', '+290', 'Saint Helena pound', 'penny', 'SHP'),
('AF', 'SL', 'SLE', '694', 'Sierra Leone', 'Freetown', '+232', 'leone', 'cent', 'SLL'),
('AF', 'SN', 'SEN', '686', 'Senegal', 'Dakar', '+221', 'CFA franc', 'centime', 'XOF'),
('AF', 'SO', 'SOM', '706', 'Somalia', 'Mogadishu', '+252', 'Somali shilling', 'cent', 'SOS'),
('AF', 'SS', 'SSN', '737', 'South Sudan', '', '', '', '', ''),
('AF', 'ST', 'STP', '678', 'Sao Tome and Principe', 'São Tomé', '+239', 'dobra', 'centavo', 'STD'),
('AF', 'SZ', 'SWZ', '748', 'Swaziland', 'Mbabane', '+268', 'lilangeni', 'cent', 'SZL'),
('AF', 'TD', 'TCD', '148', 'Chad', 'NDjamena', '+235', 'CFA franc', 'centime', 'XAF'),
('AF', 'TG', 'TGO', '768', 'Togo', 'Lomé', '', 'CFA franc79', 'centime', 'XOF'),
('AF', 'TN', 'TUN', '788', 'Tunisia', 'Tunis', '+216', 'Tunisian dinar', 'millime', 'TND'),
('AF', 'TZ', 'TZA', '834', 'Tanzania', 'Dodoma78', '+255', 'Tanzanian shilling', 'cent', 'TZS'),
('AF', 'UG', 'UGA', '800', 'Uganda', 'Kampala', '+256', 'Ugandan shilling', 'cent', 'UGX'),
('AF', 'YT', 'MYT', '175', 'Mayotte', 'Mamoudzou', '+269', 'euro', 'cent', 'EUR'),
('AF', 'ZA', 'ZAF', '710', 'South Africa', 'Pretoria73', '', 'rand', 'cent', 'ZAR'),
('AF', 'ZM', 'ZMB', '894', 'Zambia', 'Lusaka', '+260', 'Zambian kwacha', 'ngwee', 'ZMK'),
('AF', 'ZW', 'ZWE', '716', 'Zimbabwe', 'Harare', '+263', 'Zimbabwe dollar', 'cent', 'ZWD'),
('AN', 'AQ', 'ATA', '010', 'Antarctica', '', '+672', '', '', ''),
('AN', 'BV', 'BVT', '074', 'Bouvet Island', '', '', '', '', ''),
('AN', 'GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands', '', '', '', '', ''),
('AN', 'HM', 'HMD', '334', 'Heard Island and McDonald Islands', '', '', '', '', ''),
('AN', 'TF', 'ATF', '260', 'French Southern Territories', '', '', '', '', ''),
('AS', 'AE', 'ARE', '784', 'United Arab Emirates', 'Abu Dhabi', '+971', 'UAE dirham', 'fils', 'AED'),
('AS', 'AF', 'AFG', '004', 'Afghanistan', 'Kabul', '+93', 'afghani', 'pul', 'AFN'),
('AS', 'AM', 'ARM', '051', 'Armenia', 'Yerevan', '+374', 'dram', 'luma', 'AMD'),
('AS', 'AZ', 'AZE', '031', 'Azerbaijan', 'Baku', '+994', 'Azerbaijani manat', 'kepik', 'AZM'),
('AS', 'BD', 'BGD', '050', 'Bangladesh', 'Dhaka', '+880', 'taka', 'poisha', 'BDT'),
('AS', 'BH', 'BHR', '048', 'Bahrain', 'Manama', '+973', 'Bahraini dinar', 'fils', 'BHD'),
('AS', 'BN', 'BRN', '096', 'Brunei Darussalam', 'Bandar Seri Begawan', '+673', 'Brunei dollar', 'sen', 'BND'),
('AS', 'BT', 'BTN', '064', 'Bhutan', 'Thimphu', '+975', 'ngultrum', 'chhetrum', 'BTN'),
('AS', 'CC', 'CCK', '166', 'Cocos Keeling Islands', 'Bantam', '+61', 'Australian dollar', 'cent', 'AUD'),
('AS', 'CN', 'CHN', '156', 'China', 'Beijing', '+86', 'renminbi-yuan', 'jiao,  fen', 'CNY'),
('AS', 'CX', 'CXR', '162', 'Christmas Island', 'Flying Fish Cove', '+53', 'Australian dollar', 'cent', 'AUD'),
('AS', 'CY', 'CYP', '196', 'Cyprus', 'Nicosia', '+357', 'Cyprus pound', 'cent', 'CYP'),
('AS', 'GE', 'GEO', '268', 'Georgia', 'Tbilisi', '+995', 'lari', 'tetri', 'GEL'),
('AS', 'HK', 'HKG', '344', 'Hong Kong', '-', '+852', 'Hong Kong dollar', 'cent', 'HKD'),
('AS', 'ID', 'IDN', '360', 'Indonesia', 'Jakarta', '+62', 'Indonesian rupiah', 'sen', 'IDR'),
('AS', 'IL', 'ISR', '376', 'Israel', '-44', '+972', 'new shekel', 'agora', 'ILS'),
('AS', 'IN', 'IND', '356', 'India', 'New Delhi', '+91', 'Indian rupee', 'paisa', 'INR'),
('AS', 'IO', 'IOT', '086', 'British Indian Ocean Territory', '', '', '', '', ''),
('AS', 'IQ', 'IRQ', '368', 'Iraq', 'Baghdad', '+964', 'Iraqi dinar', 'fils', 'IQD'),
('AS', 'IR', 'IRN', '364', 'Iran', 'Tehran', '+98', 'Iranian rial', '-', 'IRR'),
('AS', 'JO', 'JOR', '400', 'Jordan', 'Amman', '+962', 'Jordanian dinar', 'fils', 'JOD'),
('AS', 'JP', 'JPN', '392', 'Japan', 'Tokyo', '+81', 'yen', 'sen', 'JPY'),
('AS', 'KG', 'KGZ', '417', 'Kyrgyz Republic', 'Bishkek', '+996', 'som', 'tyiyn', 'KGS'),
('AS', 'KH', 'KHM', '116', 'Cambodia', 'Phnom Penh', '+855', 'riel', 'sen', 'KHR'),
('AS', 'KP', 'PRK', '408', 'North Korea', 'Pyongyang', '+850', 'North Korean won', 'chun', 'KPW'),
('AS', 'KR', 'KOR', '410', 'South Korea', 'Seoul', '+82', 'South Korean won', 'chun', 'KRW'),
('AS', 'KW', 'KWT', '414', 'Kuwait', 'Kuwait City', '+965', 'Kuwaiti dinar', 'fils', 'KWD'),
('AS', 'KZ', 'KAZ', '398', 'Kazakhstan', 'Astana', '+7', 'tenge', 'tiyn', 'KZT'),
('AS', 'LA', 'LAO', '418', 'Lao Peoples Democratic Republic', 'Vientiane', '+856', 'kip', 'at', 'LAK'),
('AS', 'LB', 'LBN', '422', 'Lebanon', 'Beirut', '+961', 'Lebanese pound', 'piastre', 'LBP'),
('AS', 'LK', 'LKA', '144', 'Sri Lanka', 'Colombo', '+94', 'Sri Lankan rupee', 'cent', 'LKR'),
('AS', 'MM', 'MMR', '104', 'Myanmar', 'Yangon52', '+95', 'kyat', 'pya', 'MMK'),
('AS', 'MN', 'MNG', '496', 'Mongolia', 'Ulan Bator', '+976', 'tugrik', 'möngö', 'MNT'),
('AS', 'MO', 'MAC', '446', 'Macao', 'Macau', '+853', 'pataca', 'avo', 'MOP'),
('AS', 'MV', 'MDV', '462', 'Maldives', 'Malé', '+960', 'rufiyaa', 'laari', 'MVR'),
('AS', 'MY', 'MYS', '458', 'Malaysia', 'Kuala Lumpur', '+60', 'Malaysian ringgit', 'sen', 'MYR'),
('AS', 'NP', 'NPL', '524', 'Nepal', 'Kathmandu', '+977', 'Nepalese rupee', 'paisa', 'NPR'),
('AS', 'OM', 'OMN', '512', 'Oman', 'Muscat', '+968', 'Omani rial', 'baiza', 'OMR'),
('AS', 'PH', 'PHL', '608', 'Philippines', 'Manila', '', 'Philippine peso', 'centavo', 'PHP'),
('AS', 'PK', 'PAK', '586', 'Pakistan', 'Islamabad', '+92', 'Pakistani rupee', 'paisa', 'PKR'),
('AS', 'PS', 'PSE', '275', 'Palestinian Territory', '', '+970', '', '', ''),
('AS', 'QA', 'QAT', '634', 'Qatar', 'Doha', '+974 ', 'Qatari riyal', 'dirham', 'QAR'),
('AS', 'SA', 'SAU', '682', 'Saudi Arabia', 'Riyadh', '', 'Saudi riyal', 'halala', 'SAR'),
('AS', 'SG', 'SGP', '702', 'Singapore', 'Singapore', '+65', 'Singapore dollar', 'cent', 'SGD'),
('AS', 'SY', 'SYR', '760', 'Syrian Arab Republic', 'Damascus', '+963', 'Syrian pound', 'piastre', 'SYP'),
('AS', 'TH', 'THA', '764', 'Thailand', 'Bangkok', '', 'baht', 'satang', 'THB'),
('AS', 'TJ', 'TJK', '762', 'Tajikistan', 'Dushanbe', '+992', 'somoni', 'diram', 'TJS'),
('AS', 'TL', 'TLS', '626', 'Timor-Leste', 'Dili', '', 'US dollar', '-', 'USD'),
('AS', 'TM', 'TKM', '795', 'Turkmenistan', 'Ashgabat', '+993', 'Turkmen manat', 'tenge', 'TMM'),
('AS', 'TR', 'TUR', '792', 'Turkey', 'Ankara', '+90', 'Turkish lira', 'kurus', 'TRL'),
('AS', 'TW', 'TWN', '158', 'Taiwan', 'Taipei', '+886', 'new Taiwan dollar', 'fen', 'TWD'),
('AS', 'UZ', 'UZB', '860', 'Uzbekistan', 'Tashkent', '+998', 'sum', 'tiyin', 'UZS'),
('AS', 'VN', 'VNM', '704', 'Vietnam', 'Hanoi', '+84', 'dong', '-', 'VND'),
('AS', 'YE', 'YEM', '887', 'Yemen', 'Sana', '', 'Yemeni rial', 'fils', 'YER'),
('EU', 'AD', 'AND', '020', 'Andorra', 'Andorra la Vella', '+376', 'euro', 'cent', 'EUR'),
('EU', 'AL', 'ALB', '008', 'Albania', 'Tirana', '+355', 'lek', 'qindar', 'ALL'),
('EU', 'AT', 'AUT', '040', 'Austria', 'Vienna', '+43', 'euro', 'cent', 'EUR'),
('EU', 'AX', 'ALA', '248', 'Aland Islands', '', '', '', '', ''),
('EU', 'BA', 'BIH', '070', 'Bosnia and Herzegovina', 'Sarajevo', '+387', 'Bosnian convertible mark', 'fening', 'BAM'),
('EU', 'BE', 'BEL', '056', 'Belgium', 'Brussels', '+32', 'euro', 'cent', 'EUR'),
('EU', 'BG', 'BGR', '100', 'Bulgaria', 'Sofia', '+359', 'lev', 'stotinka', 'BGN'),
('EU', 'BY', 'BLR', '112', 'Belarus', 'Minsk', '+375', 'Belarusian rouble', 'kopek', 'BYR'),
('EU', 'CH', 'CHE', '756', 'Switzerland', 'Berne', '+41', 'Swiss franc', 'centime', 'CHF'),
('EU', 'CZ', 'CZE', '203', 'Czech Republic', 'Prague', '', 'Czech koruna', 'halér', 'CZK'),
('EU', 'DE', 'DEU', '276', 'Germany', 'Berlin', '+49', 'euro', 'cent', 'EUR'),
('EU', 'DK', 'DNK', '208', 'Denmark', 'Copenhagen', '+45', 'Danish krone', 'øre', 'DKK'),
('EU', 'EE', 'EST', '233', 'Estonia', 'Tallinn', '+372', 'Estonian kroon', 'sent', 'EEK'),
('EU', 'ES', 'ESP', '724', 'Spain', 'Madrid', '+34', 'euro', 'cent', 'EUR'),
('EU', 'FI', 'FIN', '246', 'Finland', 'Helsinki', '+358', 'euro', 'cent', 'EUR'),
('EU', 'FO', 'FRO', '234', 'Faroe Islands', 'Thorshavn', '+298', 'Danish krone', 'øre', 'DKK'),
('EU', 'FR', 'FRA', '250', 'France', 'Paris', '+33', 'euro', 'cent', 'EUR'),
('EU', 'GB', 'GBR', '826', 'United Kingdom of Great Britain & Northern Ireland', 'London', '+44', 'pound sterling', 'penny', 'GBP'),
('EU', 'GG', 'GGY', '831', 'Guernsey', '', '', '', '', ''),
('EU', 'GI', 'GIB', '292', 'Gibraltar', 'Gibraltar', '', 'Gibraltar pound', 'penny', 'GIP'),
('EU', 'GR', 'GRC', '300', 'Greece', 'Athens', '+30', 'euro', 'cent', 'EUR'),
('EU', 'HR', 'HRV', '191', 'Croatia', 'Zagreb', '+385', 'kuna', 'lipa', 'HRK'),
('EU', 'HU', 'HUN', '348', 'Hungary', 'Budapest', '+36', 'forint', '-', 'HUF'),
('EU', 'IE', 'IRL', '372', 'Ireland', 'Dublin', '+353', 'euro', 'cent', 'EUR'),
('EU', 'IM', 'IMN', '833', 'Isle of Man', '', '', '', '', ''),
('EU', 'IS', 'ISL', '352', 'Iceland', 'Reykjavik', '+354', 'Icelandic króna', 'eyrir', 'ISK'),
('EU', 'IT', 'ITA', '380', 'Italy', 'Rome', '+39', 'euro', 'cent', 'EUR'),
('EU', 'JE', 'JEY', '832', 'Bailiwick of Jersey', '', '', '', '', ''),
('EU', 'LI', 'LIE', '438', 'Liechtenstein', 'Vaduz', '+423', 'Swiss franc', 'centime', 'CHF'),
('EU', 'LT', 'LTU', '440', 'Lithuania', 'Vilnius', '+370', 'litas', 'centas', 'LTL'),
('EU', 'LU', 'LUX', '442', 'Luxembourg', 'Luxembourg', '+352', 'euro', 'cent', 'EUR'),
('EU', 'LV', 'LVA', '428', 'Latvia', 'Riga', '+371', 'lats', 'santims', 'LVL'),
('EU', 'MC', 'MCO', '492', 'Monaco', 'Monaco', '+377', 'euro', 'cent', 'EUR'),
('EU', 'MD', 'MDA', '498', 'Moldova', 'Chisinau', '+373', 'Moldovan leu', 'ban', 'MDL'),
('EU', 'ME', 'MNE', '499', 'Montenegro', '', '', '', '', ''),
('EU', 'MK', 'MKD', '807', 'Macedonia', 'Skopje', '+389', 'denar', 'deni', 'MKD'),
('EU', 'MT', 'MLT', '470', 'Malta', 'Valletta', '+356', 'Maltese lira', 'cent', 'MTL'),
('EU', 'NL', 'NLD', '528', 'Netherlands', 'Amsterdam54', '+31', 'euro', 'cent', 'EUR'),
('EU', 'NO', 'NOR', '578', 'Norway', 'Oslo', '+47', 'Norwegian krone', 'øre', 'NOK'),
('EU', 'PL', 'POL', '616', 'Poland', 'Warsaw', '+48', 'zloty', 'grosz', 'PLN'),
('EU', 'PT', 'PRT', '620', 'Portugal', 'Lisbon', '+351', 'euro', 'cent', 'EUR'),
('EU', 'RO', 'ROU', '642', 'Romania', 'Bucharest', '', 'Romanian leu', 'ban', 'ROL'),
('EU', 'RS', 'SRB', '688', 'Serbia', '', '', '', '', ''),
('EU', 'RU', 'RUS', '643', 'Russian Federation', 'Moscow', '+7', 'rouble', 'kopek', 'RUB'),
('EU', 'SE', 'SWE', '752', 'Sweden', 'Stockholm', '+46', 'Swedish krona', 'öre', 'SEK'),
('EU', 'SI', 'SVN', '705', 'Slovenia', 'Ljubljana', '+386', 'tolar', 'stotin', 'SIT'),
('EU', 'SJ', 'SJM', '744', 'Svalbard & Jan Mayen Islands', 'Longyearbyen76', '', 'Norwegian krone', 'øre', 'NOK'),
('EU', 'SK', 'SVK', '703', 'Slovakia', 'Bratislava', '+421', 'Slovak koruna', 'halier', 'SKK'),
('EU', 'SM', 'SMR', '674', 'San Marino', 'San Marino', '+378', 'euro', 'cent', 'EUR'),
('EU', 'UA', 'UKR', '804', 'Ukraine', 'Kiev', '+380', 'hryvnia', 'kopiyka', 'UAH'),
('EU', 'VA', 'VAT', '336', 'Vatican City State', 'Vatican City', '+418', 'euro', 'cent', 'EUR'),
('NA', 'AG', 'ATG', '028', 'Antigua and Barbuda', 'St Johns', '+1-268', 'Eastern Caribbean dollar', 'cent', 'XCD'),
('NA', 'AI', 'AIA', '660', 'Anguilla', 'The Valley', '+1-264', 'Eastern Caribbean dollar', 'cent', 'XCD'),
('NA', 'AN', 'ANT', '530', 'Netherlands Antilles', 'Willemstad', '+599', 'Netherlands Antillean guilder', 'cent', 'ANG'),
('NA', 'AW', 'ABW', '533', 'Aruba', 'Oranjestad', '+297', 'Aruban guilder', 'cent', 'AWG'),
('NA', 'BB', 'BRB', '052', 'Barbados', 'Bridgetown', '+1-246', 'Barbados dollar', 'cent', 'BBD'),
('NA', 'BL', 'BLM', '652', 'Saint Barthelemy', '', '', '', '', ''),
('NA', 'BM', 'BMU', '060', 'Bermuda', 'Hamilton', '+1-441', 'Bermuda dollar', 'cent', 'BMD'),
('NA', 'BS', 'BHS', '044', 'Bahamas', 'Nassau', '+1-242', 'Bahamian dollar', 'cent', 'BSD'),
('NA', 'BZ', 'BLZ', '084', 'Belize', 'Belmopan', '+501', 'Belize dollar', 'cent', 'BZD'),
('NA', 'CA', 'CAN', '124', 'Canada', 'Ottawa', '+1', 'Canadian dollar', 'cent', 'CAD'),
('NA', 'CR', 'CRI', '188', 'Costa Rica', 'San José', '+506', 'Costa Rican colón', 'céntimo', 'CRC'),
('NA', 'CU', 'CUB', '192', 'Cuba', 'Havana', '+53', 'Cuban peso', 'centavo', 'CUP'),
('NA', 'DM', 'DMA', '212', 'Dominica', 'Roseau', '+1-767', 'Eastern Caribbean dollar', 'cent', 'XCD'),
('NA', 'DO', 'DOM', '214', 'Dominican Republic', 'Santo Domingo', '+1-809', 'Dominican peso', 'centavo', 'DOP'),
('NA', 'GD', 'GRD', '308', 'Grenada', 'St Georges', '+1-473', 'Eastern Caribbean dollar', 'cent', 'XCD'),
('NA', 'GL', 'GRL', '304', 'Greenland', 'Nuuk', '+299', 'Danish krone', 'øre', 'DKK'),
('NA', 'GP', 'GLP', '312', 'Guadeloupe', 'Basse Terre', '+590', 'euro', 'cent', 'EUR'),
('NA', 'GT', 'GTM', '320', 'Guatemala', 'Guatemala City', '+502', 'Guatemalan quetzal', 'centavo', 'GTQ'),
('NA', 'HN', 'HND', '340', 'Honduras', 'Tegucigalpa', '+504', 'lempira', 'centavo', 'HNL'),
('NA', 'HT', 'HTI', '332', 'Haiti', 'Port-au-Prince', '', 'gourde', 'centime', 'HTG'),
('NA', 'JM', 'JAM', '388', 'Jamaica', 'Kingston', '+1-876', 'Jamaica dollar', 'cent', 'JMD'),
('NA', 'KN', 'KNA', '659', 'Saint Kitts and Nevis', 'Basseterre', '+1-869', 'Eastern Caribbean dollar', 'cent', 'XCD'),
('NA', 'KY', 'CYM', '136', 'Cayman Islands', 'George Town', '+1-345', 'Cayman Islands dollar', 'cent', 'KYD'),
('NA', 'LC', 'LCA', '662', 'Saint Lucia', 'Castries', '+1-758', 'Eastern Caribbean dollar', 'cent', 'XCD'),
('NA', 'MF', 'MAF', '663', 'Saint Martin', '', '', '', '', ''),
('NA', 'MQ', 'MTQ', '474', 'Martinique', 'Fort-de-France', '+596', 'euro', 'cent', 'EUR'),
('NA', 'MS', 'MSR', '500', 'Montserrat', 'Plymouth', '+1-664', 'Eastern Caribbean dollar', 'cent', 'XCD'),
('NA', 'MX', 'MEX', '484', 'Mexico', 'Mexico City', '+52', 'Mexican peso', 'centavo', 'MXN'),
('NA', 'NI', 'NIC', '558', 'Nicaragua', 'Managua', '+505', 'córdoba', 'centavo', 'NIO'),
('NA', 'PA', 'PAN', '591', 'Panama', 'Panama City', '+507', 'balboa', 'centésimo', 'PAB'),
('NA', 'PM', 'SPM', '666', 'Saint Pierre and Miquelon', 'Saint-Pierre', '+508', 'euro', 'cent', 'EUR'),
('NA', 'PR', 'PRI', '630', 'Puerto Rico', 'San Juan', '+1-787', 'US dollar', 'cent', 'USD'),
('NA', 'SV', 'SLV', '222', 'El Salvador', 'San Salvador', '+503', 'US dollar', 'centavo', 'USD'),
('NA', 'TC', 'TCA', '796', 'Turks and Caicos Islands', 'Cockburn Town', '+1-649', 'US dollar', 'cent', 'USD'),
('NA', 'TT', 'TTO', '780', 'Trinidad and Tobago', 'Port of Spain', '', 'Trinidad and Tobago dollar', 'cent', 'TTD'),
('NA', 'US', 'USA', '840', 'United States of America', 'Washington DC', '', 'US dollar', 'cent', 'USD'),
('NA', 'VC', 'VCT', '670', 'Saint Vincent and the Grenadines', 'Kingstown', '+1-784', 'Eastern Caribbean dollar', 'cent', 'XCD'),
('NA', 'VG', 'VGB', '092', 'British Virgin Islands', 'Road Town', '', 'US dollar', 'cent', 'USD'),
('NA', 'VI', 'VIR', '850', 'United States Virgin Islands', 'Charlotte Amalie', '+1-284', 'US dollar', 'cent', 'USD'),
('OC', 'AS', 'ASM', '016', 'American Samoa', 'Pago Pago', '+1-684', 'US dollar', 'cent', 'USD'),
('OC', 'AU', 'AUS', '036', 'Australia', 'Canberra', '+61', 'Australian dollar', 'cent', 'AUD'),
('OC', 'CK', 'COK', '184', 'Cook Islands', 'Avarua', '+682', 'New Zealand dollar', 'cent', 'NZD'),
('OC', 'FJ', 'FJI', '242', 'Fiji', 'Suva', '+679', 'Fiji dollar', 'cent', 'FJD'),
('OC', 'FM', 'FSM', '583', 'Micronesia', 'Palikir', '+691', 'US dollar', 'cent', 'USD'),
('OC', 'GU', 'GUM', '316', 'Guam', 'Hagåtña', '+1-671', 'US dollar', 'cent', 'USD'),
('OC', 'KI', 'KIR', '296', 'Kiribati', 'Tarawa', '+686', 'Australian dollar', 'cent', 'AUD'),
('OC', 'MH', 'MHL', '584', 'Marshall Islands', 'Majuro', '+692', 'US dollar', 'cent', 'USD'),
('OC', 'MP', 'MNP', '580', 'Northern Mariana Islands', 'Garapan62', '+1-670', 'US dollar', 'cent', 'USD'),
('OC', 'NC', 'NCL', '540', 'New Caledonia', 'Nouméa', '+687', 'CFP franc', 'centime', 'XPF'),
('OC', 'NF', 'NFK', '574', 'Norfolk Island', 'Kingston', '+672', 'Australian dollar', 'cent', 'AUD'),
('OC', 'NR', 'NRU', '520', 'Nauru', 'Yaren', '+674', 'Australian dollar', 'cent', 'AUD'),
('OC', 'NU', 'NIU', '570', 'Niue', 'Alofi', '+683', 'New Zealand dollar', 'cent', 'NZD'),
('OC', 'NZ', 'NZL', '554', 'New Zealand', 'Wellington', '+64', 'New Zealand dollar', 'cent', 'NZD'),
('OC', 'PF', 'PYF', '258', 'French Polynesia', 'Papeete', '', 'CFP franc', 'centime', 'XPF'),
('OC', 'PG', 'PNG', '598', 'Papua New Guinea', 'Port Moresby', '+675', 'kina', 'toea', 'PGK'),
('OC', 'PN', 'PCN', '612', 'Pitcairn Islands', 'Adamstown', '', 'New Zealand dollar', 'cent', 'NZD'),
('OC', 'PW', 'PLW', '585', 'Palau', 'Koror', '+680', 'US dollar', 'cent', 'USD'),
('OC', 'SB', 'SLB', '090', 'Solomon Islands', 'Honiara', '+677', 'Solomon Islands dollar', 'cent', 'SBD'),
('OC', 'TK', 'TKL', '772', 'Tokelau', 'Fakaofo', '+690', 'New Zealand dollar', 'cent', 'NZD'),
('OC', 'TO', 'TON', '776', 'Tonga', 'Nukualofa', '+676', 'paanga', 'seniti', 'TOP'),
('OC', 'TV', 'TUV', '798', 'Tuvalu', 'Fongafale82', '+688', 'Australian dollar', 'cent', 'AUD'),
('OC', 'UM', 'UMI', '581', 'United States Minor Outlying Islands', '', '', '', '', ''),
('OC', 'VU', 'VUT', '548', 'Vanuatu', 'Port Vila', '+678', 'vatu', '-', 'VUV'),
('OC', 'WF', 'WLF', '876', 'Wallis and Futuna', 'Mata-Utu', '', 'CFP franc', 'centime', 'XPF'),
('OC', 'WS', 'WSM', '882', 'Samoa', 'Apia', '+685', 'tala', 'sene', 'WST'),
('SA', 'AR', 'ARG', '032', 'Argentina', 'Buenos Aires', '+54', 'Argentine peso', 'centavo', 'ARS'),
('SA', 'BO', 'BOL', '068', 'Bolivia', 'Sucre16', '+591', 'boliviano', 'centavo', 'BOB'),
('SA', 'BR', 'BRA', '076', 'Brazil', 'Brasilia', '', 'Brazilian real', 'centavo', 'BRL'),
('SA', 'CL', 'CHL', '152', 'Chile', 'Santiago', '+56', 'Chilean peso', 'centavo', 'CLP'),
('SA', 'CO', 'COL', '170', 'Colombia', 'Santa Fe de Bogotá', '+57', 'Colombian peso', 'centavo', 'COP'),
('SA', 'EC', 'ECU', '218', 'Ecuador', 'Quito', '+593', 'US dollar', '-', 'USD'),
('SA', 'FK', 'FLK', '238', 'Falkland Islands', 'Stanley', '+500', 'Falkland Islands pound', 'new penny', 'FKP'),
('SA', 'GF', 'GUF', '254', 'French Guiana', 'Cayenne', '+594', 'euro', 'cent', 'EUR'),
('SA', 'GY', 'GUY', '328', 'Guyana', 'Georgetown', '+592', 'Guyanese dollar', 'cent', 'GYD'),
('SA', 'PE', 'PER', '604', 'Peru', 'Lima', '+51', 'new sol', 'céntimo', 'PEN'),
('SA', 'PY', 'PRY', '600', 'Paraguay', 'Asunción', '+595', 'guaraní', 'céntimo', 'PYG'),
('SA', 'SR', 'SUR', '740', 'Suriname', 'Paramaribo', '', 'Suriname guilder', 'cent', 'SRG'),
('SA', 'UY', 'URY', '858', 'Uruguay', 'Montevideo', '+598', 'Uruguayan peso', 'centésimo', 'UYU'),
('SA', 'VE', 'VEN', '862', 'Venezuela', 'Caracas', '+58', 'bolívar', 'centavo', 'VEB');
